export { yandexHelp, tests as yandexHelpTests } from './YANDEX.HELP';
export { restart, tests as restartTests } from './restart';
export { spiralAnswerNo, tests as spiralAnswerNoTests } from './spiral.answer.no';
export { spiralAnswerUnsure, tests as spiralAnswerUnsureTests } from './spiral.answer.unsure';
export { spiralAnswerYes, tests as spiralAnswerYesTests } from './spiral.answer.yes';
export { spiralContinue, tests as spiralContinueTests } from './spiral.continue';
export { spiralDescribe, tests as spiralDescribeTests } from './spiral.describe';
export { spiralDescribeBeige, tests as spiralDescribeBeigeTests } from './spiral.describe.beige';
export { spiralDescribeRed, tests as spiralDescribeRedTests } from './spiral.describe.red';
export { spiralDescribeOrange, tests as spiralDescribeOrangeTests } from './spiral.describe.orange';
export { spiralDescribeYellow, tests as spiralDescribeYellowTests } from './spiral.describe.yellow';
export { spiralDescribeGreen, tests as spiralDescribeGreenTests } from './spiral.describe.green';
export { spiralDescribeBlue, tests as spiralDescribeBlueTests } from './spiral.describe.blue';
export { spiralDescribePurple, tests as spiralDescribePurpleTests } from './spiral.describe.purple';
export { spiralDescribeTurquoise, tests as spiralDescribeTurquoiseTests } from './spiral.describe.turquoise';
export { spiralError, tests as spiralErrorTests } from './spiral.error';
export { spiralExit, tests as spiralExitTests } from './spiral.exit';
export { spiralPause, tests as spiralPauseTests } from './spiral.pause';
export { spiralRepeat, tests as spiralRepeatTests } from './spiral.repeat';
export { spiralRepeatResults, tests as spiralRepeatResultsTests } from './spiral.repeat_results';
export { spiralRestart, tests as spiralRestartTests } from './spiral.restart';
export { spiralStart, tests as spiralStartTests } from './spiral.start';
export { spiralNo, tests as spiralNoTests } from './spiral.no';
export { spiralYes, tests as spiralYesTests } from './spiral.yes';
export declare const ALL_INTENTS: string[];
//# sourceMappingURL=index.d.ts.map